GET {{app}}/findUser?name=Francesca
Content-Type: application/json
Accept: application/json

###

GET {{app}}/test
Content-Type: application/json
Accept: application/json

###

POST {{app}}/addUser
Content-Type: application/json
Accept: application/json

{
  "name": "Alfredo2",
  "email": "alfredocospito@gmail.com",
  "age": 24
}

### Arduino test request

POST {{app}}/arduino/test
Content-Type: application/json
Accept: application/json

{
  "number": 789
}